### ISSUE TITLE
Unable to turn off gifs

### ISSUE THREAD

**Issue by tinkone** [dblock/slack-gamebot#101]
`pongbot set gifs off` appears to be broken, the return response `is invalid`. And gifs continue to be shown.

**Comment by dblock** [comment]
(Re)tested which worked for me, but I see an error in the logs. I don't see the stack for it, so a bit hard to debug. Does your team start with "365"? Otherwise what's the team name?

Are you typing this in a channel? Care to screenshot it? 

Try a few variations:

- `@pongbot: set gifs off`
- `@pongbot set gifs off`

Or DM the bot

- `set gifs off`

Same error?

**Comment by tinkone** [comment]
Yeah the team name starts with `365`, I just DM the bot with `set gifs off` still get the `invalid` message back. Here's the screen cap, hope it brings some clarity

![screen shot 2016-04-08 at 8 50 23 am](https://cloud.githubusercontent.com/assets/12869296/14389366/2eac0f42-fd67-11e5-8608-3824f4305919.png)

**Comment by dblock** [comment]
Does `set gifs` return anything or also errors out?

**Comment by dblock** [comment]
I've made some logging improvements in production, do try again, that should help with locating the problem. Appreciate your patience.

**Comment by tinkone** [comment]
Hey that seems to fix it. I can set it on and off now. Sweet!

**Comment by dblock** [comment]
Strange. I didn't change any code around setting these, something must still be an issue. I'll close this for now.

**Comment by dblock** [comment]
This should be now fixed, see #102.
